print("Nama : Rico Prasetya")
print("NIM : 312210425")
print()
print("Hello")
print("Saya Sedang Belajar Python")
print()
a=input("Masukkan nilai a=")
b=input("Masukkan nilai b=")
print()
print("Variabel a=",a)
print("Variabel b=",b)
print()
print("Hasil penggabungan {0}&{1}={2}".format(a,b,a+b))
a=int(a)
b=int(b)
print("Hasil penjumlahan {0}+{1}={2}".format(a,b,a+b))
print("Hasil pembagian {0}/{1}={2}".format(a,b,a/b))